In [1]:
!pip install numpy pandas scikit-learn seaborn

Requirement already satisfied: numpy in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (3.0.5)
Requirement already satisfied: scikit-learn in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (1.9.0)
Requirement already satisfied: seaborn in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\hira0mi\Desktop\job_preparation\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
df = pd.read_csv('../datasets/Titanic-Dataset.csv', index_col='PassengerId')
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    str
 3   Sex       891 non-null    str
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    str
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    str
 10  Embarked  889 non-null    str
dtypes: float64(2), int64(4), str(5)
memory usage: 76.7 KB

In [7]:
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [8]:
df.isnull().sum()

Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [9]:
df['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [10]:
df.dtypes

Survived      int64
Pclass        int64
Name            str
Sex             str
Age         float64
SibSp         int64
Parch         int64
Ticket          str
Fare        float64
Cabin           str
Embarked        str
dtype: object

Проверял, зависит ли выживаемость от пола. Зависит, причём сильно, женщины сильно чаще мужчин выживали

In [11]:
df.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Очевидно, чем круче класс, тем с большей вероятностью пассажир выжил. Это действительно так

In [12]:
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Оказалось, от порта высадки также зависит выживаемость

In [13]:
df.groupby('Embarked')['Survived'].mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [14]:
df.groupby('Parch')['Survived'].mean()

Parch
0    0.343658
1    0.550847
2    0.500000
3    0.600000
4    0.000000
5    0.200000
6    0.000000
Name: Survived, dtype: float64

Parch тут - родители + дети, если таковые есть, а SibSp - количество сиблингов(братьев\сестёр), если таковые есть. Складываем, прибавляем 1 потому что 1 человек в семье точно есть, раз он на титанике и получаем размер семьи

In [15]:
df['FamilySize'] = df['Parch'] + df['SibSp'] + 1

Одна из самых распространённых гипотез при исследовании этого датасета, люди с "умеренным" FamilySize выживали чаще, чем остальные. Гипотеза оказалась правдивой

In [16]:
df.groupby('FamilySize')['Survived'].mean()

FamilySize
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64

Где-то подсмотрел предположение, что у людей с неуказанной кабиной меньше шансов выжить

In [17]:
df['HasCabin'] = df['Cabin'].notna()#+категориальный признак

In [18]:
df['isFemale'] = np.where(df['Sex'] == 'female', 1, 0)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Name        891 non-null    str
 3   Sex         891 non-null    str
 4   Age         714 non-null    float64
 5   SibSp       891 non-null    int64
 6   Parch       891 non-null    int64
 7   Ticket      891 non-null    str
 8   Fare        891 non-null    float64
 9   Cabin       204 non-null    str
 10  Embarked    889 non-null    str
 11  FamilySize  891 non-null    int64
 12  HasCabin    891 non-null    bool
 13  isFemale    891 non-null    int64
dtypes: bool(1), float64(2), int64(6), str(5)
memory usage: 91.5 KB

Знаю, что лучше pd.get_dummies(), но почему бы не сделать OHE самому?

In [20]:
df['Q_Embarked'] = np.where(df['Embarked'] == 'Q', 1, 0)
df['S_Embarked'] = np.where(df['Embarked'] == 'S', 1, 0)
df['C_Embarked'] = np.where(df['Embarked'] == 'C', 1, 0)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Name        891 non-null    str
 3   Sex         891 non-null    str
 4   Age         714 non-null    float64
 5   SibSp       891 non-null    int64
 6   Parch       891 non-null    int64
 7   Ticket      891 non-null    str
 8   Fare        891 non-null    float64
 9   Cabin       204 non-null    str
 10  Embarked    889 non-null    str
 11  FamilySize  891 non-null    int64
 12  HasCabin    891 non-null    bool
 13  isFemale    891 non-null    int64
 14  Q_Embarked  891 non-null    int64
 15  S_Embarked  891 non-null    int64
 16  C_Embarked  891 non-null    int64
dtypes: bool(1), float64(2), int64(9), str(5)
memory usage: 112.4 KB

In [22]:
df.isnull().sum()

Survived        0
Pclass          0
Name            0
Sex             0
Age           177
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin         687
Embarked        2
FamilySize      0
HasCabin        0
isFemale        0
Q_Embarked      0
S_Embarked      0
C_Embarked      0
dtype: int64

В Embarked пропусков не боюсь, все пропуски у нас просто будут 0 0 0, тем более их мало. А с возрастом надо что-то сделать. Я решил не заморачиваться и заполнить всё средним

In [23]:
mean_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_age)

In [24]:
print(df.head())
print(df.info())

             Survived  Pclass  \
PassengerId
1                   0       3
2                   1       1
3                   1       3
4                   1       1
5                   0       3

                                                          Name     Sex   Age  \
PassengerId
1                                      Braund, Mr. Owen Harris    male  22.0
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
3                                       Heikkinen, Miss. Laina  female  26.0
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
5                                     Allen, Mr. William Henry    male  35.0

             SibSp  Parch            Ticket     Fare Cabin Embarked  \
PassengerId
1                1      0         A/5 21171   7.2500   NaN        S
2                1      0          PC 17599  71.2833   C85        C
3                0      0  STON/O2. 3101282   7.9250   NaN        S
4                1      0            113803  53.1000  C123        S
5                0      0            373450   8.0500   NaN        S

             FamilySize  HasCabin  isFemale  Q_Embarked  S_Embarked  \
PassengerId
1                     2     False         0           0           1
2                     2      True         1           0           0
3                     1     False         1           0           1
4                     2      True         1           0           1
5                     1     False         0           0           1

             C_Embarked
PassengerId
1                     0
2                     1
3                     0
4                     0
5                     0
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Name        891 non-null    str
 3   Sex         891 non-null    str
 4   Age         891 non-null    float64
 5   SibSp       891 non-null    int64
 6   Parch       891 non-null    int64
 7   Ticket      891 non-null    str
 8   Fare        891 non-null    float64
 9   Cabin       204 non-null    str
 10  Embarked    889 non-null    str
 11  FamilySize  891 non-null    int64
 12  HasCabin    891 non-null    bool
 13  isFemale    891 non-null    int64
 14  Q_Embarked  891 non-null    int64
 15  S_Embarked  891 non-null    int64
 16  C_Embarked  891 non-null    int64
dtypes: bool(1), float64(2), int64(9), str(5)
memory usage: 112.4 KB
None

In [25]:
#избавился от признаков, которые мне теперь не нужны. 
df = df.drop(columns=[
    'Name',
    'Ticket',
    'Cabin',
    'Embarked',
    'Sex',
    
])

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Age         891 non-null    float64
 3   SibSp       891 non-null    int64
 4   Parch       891 non-null    int64
 5   Fare        891 non-null    float64
 6   FamilySize  891 non-null    int64
 7   HasCabin    891 non-null    bool
 8   isFemale    891 non-null    int64
 9   Q_Embarked  891 non-null    int64
 10  S_Embarked  891 non-null    int64
 11  C_Embarked  891 non-null    int64
dtypes: bool(1), float64(2), int64(9)
memory usage: 77.6 KB

In [27]:
X = df.drop(columns=["Survived"])
y = df["Survived"]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

In [29]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [30]:
y_pred = model.predict(X_test)

In [31]:
accuracy = accuracy_score(y_test, y_pred)

In [32]:
print(accuracy)

0.8171641791044776

In [33]:
model.coef_

array([[-6.97218873e-01, -3.40215051e-02, -1.52362978e-01,
         1.88012063e-02,  2.10770268e-03, -1.14036286e-01,
         6.35799596e-01,  2.47085604e+00,  3.96348855e-02,
        -3.49194326e-01,  2.13316574e-01]])

In [34]:
from sklearn.metrics import precision_score, f1_score, roc_auc_score
#от безделия вычислил другие метрики
precision = precision_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

In [35]:
precision, f1, roc_auc

(0.81, 0.7677725118483413, 0.8043553107247375)